import React, { createContext, useContext, useState, useEffect } from "react";
import { useSettings } from "../hooks/useSettings";
import { useAuth } from "./AuthContext";

type Language = "uz" | "ru";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (text: string) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

// Translation dictionary
const dictionary: Record<string, string> = {
  // Navigation
  "Asosiy": "Главная",
  "Kassa": "Касса",
  "Tovarlar": "Товары",
  "Tarix": "История",
  "Mijozlar": "Клиенты",
  "Sozlamalar": "Настройки",

  // Dashboard
  "Bugungi savdolar": "Сегодняшние продажи",
  "Kunlik tushum": "Ежедневная выручка",
  "Umumiy qarzlar": "Общие долги",
  "Faol foydalanuvchilar": "Активные пользователи",
  "Statistika": "Статистика",
  "Haftalik savdo grafigi": "Еженедельный график продаж",
  "Ombor qoldig'i holati": "Состояние остатков на складе",
  "Kutilayotgan so'rovlar": "Ожидающие запросы",
  "Ogohlantirishlar": "Предупреждения",
  "Ishchi arizalari": "Заявки работников",
  "Sotuvchilar ulushi": "Доли продавцов",
  "Yuklanmoqda...": "Загрузка...",
  "Hech qanday ogohlantirish yo'q": "Нет предупреждений",
  "Kam qolgan tovarlar": "Малооставшиеся товары",
  "Muddati yaqinlashayotgan tovarlar": "Товары с истекающим сроком",
  "Bugun savdolar amalga oshirilmagan": "Сегодня продажи не совершались",
  "hafta": "неделя",
  "Bugungi sana:": "Дата:",
  "Bugungi savdo": "Сегодняшние продажи",
  "Sotuv soni": "Кол-во продаж",
  "Bugungi tushum": "Сегодняшняя выручка",
  "Bugungi sof foyda": "Сегодняшняя чистая прибыль",
  "Savdo tendensiyasi": "Тенденция продаж",
  "So'nggi savdolar": "Последние продажи",
  "dona mahsulot": "шт. товара",
  "Barcha tranzaksiyalar": "Все транзакции",
  "Ombor holati": "Состояние склада",
  "Tovarlar turi": "Виды товаров",
  "xil": "наим.",
  "Jami dona": "Всего шт.",
  "Ombor tan narxi": "Себестоимость склада",
  "Sotuv qiymati": "Стоимость продажи",
  "Mahsulotlar ro'yxatiga o'tish": "Перейти к списку товаров",
  "Ma'lumotlar zaxirasi": "Резервная копия данных",
  "Tayyorlanmoqda...": "Подготовка...",
  "Backup yuklab olish": "Скачать бэкап",
  "ta": "шт.",

  // POS
  "Savdo bo'limi": "Отдел продаж",
  "Savat": "Корзина",
  "Mijoz tanlang...": "Выберите клиента...",
  "Shtrix-kod (Skaner)": "Штрих-код (Сканер)",
  "Shtrix-kod yoki nomini yozing...": "Введите штрих-код или название...",
  "Qidirish...": "Поиск...",
  "Savat bo'sh": "Корзина пуста",
  "Jami:": "Итого:",
  "To'lov qilish": "Оплатить",
  "To'lov turi": "Способ оплаты",
  "Naqd": "Наличные",
  "Plastik": "Карта",
  "Qarz": "В долг",
  "Aralash": "Смешанный",
  "To'langan summa": "Оплаченная сумма",
  "Qarz summasi": "Сумма долга",
  "Sotish": "Продать",
  "Savdo muvaffaqiyatli yakunlandi!": "Продажа успешно завершена!",
  "Chek chop etish": "Печать чека",
  "Yopish": "Закрыть",
  "Savdoni tasdiqlash": "Подтверждение продажи",
  "Telefon raqami": "Номер телефона",
  "Qidiruv": "Поиск",
  "Tanlang": "Выбрать",
  "Yangi mijoz qo'shish": "Добавить нового клиента",
  "Ismi": "Имя",
  "Telefon": "Телефон",
  "Qo'shish": "Добавить",
  "Bekor qilish": "Отмена",
  "Tan narxi (UZS)": "Себестоимость (UZS)",
  "Sotuv narxi (UZS)": "Цена продажи (UZS)",
  "Ombor qoldig'i (kg)": "Остаток на складе (кг)",
  "Ombor qoldig'i (dona)": "Остаток на складе (шт)",
  "Ombor qoldig'i (m)": "Остаток на складе (м)",
  "Shtrix-kod (Skanner)": "Штрих-код (Сканер)",
  "Maslahat: Jismoniy skaner quroli yordamida shtrix-kodni to'g'ridan-to'g'ri skanerlashingiz ham mumkin.": "Совет: Вы также можете сканировать штрих-код напрямую с помощью физического сканера.",
  "Mahsulot rasmi": "Изображение товара",
  "Rasm yo'q": "Нет фото",
  "Rasm tanlash": "Выбрать фото",
  "Saqlash": "Сохранить",
  "Saqlanmoqda...": "Сохранение...",
  "Telefon raqami noto'g'ri": "Неверный номер телефона",
  "Qarzga sotish uchun mijoz tanlanishi shart": "Для продажи в долг необходимо выбрать клиента",
  "Savatga qo'shish": "Добавить в корзину",
  "Xato yuz berdi": "Произошла ошибка",
  "Mavjud mijozlar": "Существующие клиенты",
  "Mijoz ismi (majburiy)": "Имя клиента (обязательно)",
  "Telegram orqali yuborish": "Отправить через Telegram",
  "Barcode qidirish": "Поиск штрих-кода",
  "Barcode yoki ID raqami...": "Штрих-код или ID номер...",
  "Maslahat: Jismoniy skaner quroli ulangan bo'lsa, hech qanday tugmani bosmasdan mahsulot shtrix-kodini shunchaki skanerlang, savatga avtomatik qo'shiladi.": "Совет: Если подключен физический сканер, просто отсканируйте штрих-код товара без нажатия каких-либо кнопок, он будет добавлен в корзину автоматически.",
  "Qarz oluvchi mijozni tanlang...": "Выберите клиента-должника...",
  "Mijoz biriktirish (ixtiyoriy)": "Прикрепить клиента (опционально)",
  "Hozir to'lanadigan qismi (ixtiyoriy)": "Оплачиваемая сейчас часть (опционально)",
  "Jami summa:": "Итоговая сумма:",
  "Mijoz tanlash": "Выбор клиента",
  "Umumiy summa:": "Общая сумма:",
  "Sotuv narxi:": "Цена продажи:",
  "Miqdor": "Количество",
  "Summa (so'm)": "Сумма (сум)",
  "Chek formatini tanlang:": "Выберите формат чека:",
  "Yuklash": "Скачать",
  "Kg": "кг",

  // Products
  "Tovarlar ro'yxati": "Список товаров",
  "Yangi tovar qo'shish": "Добавить новый товар",
  "Qidirish... (nomi, brendi)": "Поиск... (название, бренд)",
  "Skaner": "Сканер",
  "Stokda": "В наличии",
  "Mahsulotni o'chirish": "Удаление товара",
  "Haqiqatan ham bu mahsulotni o'chirishni istaysizmi?": "Вы действительно хотите удалить этот товар?",
  "O'chirish": "Удалить",
  "O'chirish so'rovi yuborildi": "Запрос на deletion отправлен",
  "Xodim bo'lganingiz sababli mahsulotni o'chirish uchun rahbarga o'chirish so'rovi yuboriladi. Tasdiqlaysizmi?": "Поскольку вы являетесь сотрудником, для удаления товара менеджеру будет отправлен запрос на удаление. Подтверждаете?",
  "Mahsulotni o'chirishda xato yuz berdi": "Произошла ошибка при удалении товара",
  "So'rov yuborishda xato yuz berdi": "Произошла ошибка при отправке запроса",
  "Mahsulotlar": "Товары",
  "Do'kon omboridagi barcha tovarlar ro'yxati": "Список всех товаров на складе магазина",
  "Yangi tovar": "Новый товар",
  "Mahsulot formasi": "Форма товара",
  "Nomi, brendi yoki shtrix-kodi bo'yicha qidirish...": "Поиск по названию, бренду или штрих-коду...",
  "ta mahsulot omborda kam qoldi (5 tadan kam)": "товаров мало на складе (меньше 5)",
  "Ko'rish": "Смотреть",
  "Barchasi": "Все",
  "Dona": "Штука",
  "Kilogramm": "Килограмм",
  "Metr": "Метр",
  "Natija:": "Результат:",
  "ta tovar": "товаров",
  "Tartiblash:": "Сортировка:",
  "Nom": "Имя",
  "Sotuv": "Продажа",
  "Soni": "Кол-во",
  "Mahsulotlar yuklanmoqda...": "Загрузка товаров...",
  "Hech narsa topilmadi": "Ничего не найдено",
  "qidiruviga mos mahsulot yo'q": "товаров по поиску нет",
  "Hozircha mahsulot qo'shilmagan": "Товары пока не добавлены",
  "Tovar qo'shish": "Добавить товар",
  "Kam qoldi": "Мало осталось",
  "Tan:": "Себ:",
  "Sotuv:": "Прод:",
  "Tizim raxbari so'rovni ko'rib chiqib tasdiqlagach, ushbu mahsulot ro'yxatdan o'chiriladi.": "После рассмотрения и одобрения руководителем этот товар будет удален из списка.",
  "Raxbardan ruxsat so'rash": "Запросить разрешение у руководителя",
  "mahsulotini o'chirish bo'yicha rahbariyatga so'rov yuborilsinmi?": "отправить запрос руководству на удаление товара?",
  "Yo'q, bekor qilish": "Нет, отменить",
  "Tovarni o'chirish": "Удалить товар",
  "Ushbu amalni ortga qaytarib bo'lmaydi": "Это действие нельзя отменить",
  "mahsulotini do'kon bazasidan butunlay o'chirasizmi?": "удалить товар из базы магазина навсегда?",
  "O'chirilmoqda...": "Удаление...",
  "Ha, o'chirilsin": "Да, удалить",
  "O'lchov birligi": "Единица измерения",
  "Mahsulot nomi": "Название продукта",
  "Barcode raqami...": "Номер штрих-кода...",
  "Tovarni tahrirlash": "Редактировать товар",

  // History
  "Savdolar tarixi": "История продаж",
  "Sana": "Дата",
  "Summa": "Сумма",
  "Holat": "Статус",
  "Amal": "Действие",
  "Batafsil": "Подробнее",
  "Faktura PDF": "Фактура PDF",
  "Chek PDF": "Чек PDF",
  "Yuk xati PDF": "Накладная PDF",
  "Savdoni bekor qilish": "Отмена продажи",
  "Savdoni bekor qilishni tasdiqlaysizmi? Mahsulotlar zaxirasi tiklanadi.": "Подтверждаете отмену продажи? Запас товаров восстановится.",
  "Faktura": "Фактура",
  "Chek": "Чек",
  "Yuk xati": "Накладная",
  "Hujjatlar:": "Документы:",
  "Sotilgan tovarlar:": "Проданные товары:",
  "dona": "шт.",
  "Jami to'lov:": "Итого к оплате:",
  "O'chirishda xatolik yuz berdi": "Произошла ошибка при удалении",
  "So'rov yuborishda xatolik": "Ошибка отправки запроса",
  "ta tanlandi": "выбрано",
  "Hammasini tanlash": "Выбрать все",
  "Savdo tarixi": "История продаж",
  "Tranzaksiyalar va sotuv fakturalarini boshqarish": "Управление транзакциями и счетами продаж",
  "Sotuvlar": "Продажи",
  "Jami tushum": "Общая выручка",
  "Uzoq bosish orqali tanlang": "Выберите долгим нажатием",
  "Jami o'chirish": "Удалить все",
  "Savdolar yuklanmoqda...": "Загрузка продаж...",
  "Sotuvlar tarixi bo'sh": "История продаж пуста",
  "POS kassa bo'limidan birinchi sotuvni amalga oshiring": "Совершите первую продажу в разделе POS кассы",
  "Savdo tarixini o'chirish": "Удалить историю продаж",
  "Haqiqatdan ham barcha sotuvlar tarixini butunlay o'chirib tashlaysizmi? Tovar qoldiqlari avtomatik ravishda tiklanadi.": "Вы действительно хотите полностью удалить всю историю продаж? Остатки товаров восстановятся автоматически.",
  "ta sotuv tarixini o'chirasizmi? Tovar qoldiqlari tiklanadi.": "удалить историю продаж? Остатки товаров восстановятся.",
  "Ushbu amalni ortga qaytarib bo'lmaydi!": "Это действие нельзя отменить!",
  "Rahbar so'rovni ko'rib chiqib tasdiqlaganidan so'ng ushbu savdo ma'lumotlari o'chiriladi.": "После рассмотрения и одобрения руководителем эти данные о продажах будут удалены.",
  "O'chirish so'rovi yuborish": "Отправить запрос на удаление",
  "Rahbar tasdig'i lozim": "Требуется подтверждение руководителя",
  "Barcha savdolar tarixini o'chirish bo'yicha rahbariyatga so'rov yuborilsinmi?": "Отправить запрос руководству на удаление всей истории продаж?",
  "ta savdo tarixini o'chirish bo'yicha rahbariyatga so'rov yuborilsinmi?": "отправить запрос руководству на удаление истории продаж?",
  "Ha, yuborish": "Да, отправить",
  "Yuborilmoqda...": "Отправка...",

  // Customers
  "Mijozlar ro'yxati": "Список клиентов",
  "Yangi mijoz": "Новый клиент",
  "Qarz miqdori": "Сумма долга",
  "Qidirish... (Ismi, tel)": "Поиск... (Имя, тел)",
  "Mijoz haqida batafsil": "Подробнее о клиенте",
  "Telefon:": "Телефон:",
  "Umumiy savdolar:": "Всего продаж:",
  "Umumiy to'lovlar:": "Всего оплат:",
  "Joriy qarz:": "Текущий долг:",
  "Qarzni to'lash": "Погасить долг",
  "To'lovlar tarixi": "История оплат",
  "Hali to'lovlar amalga oshirilmagan": "Оплат еще не производилось",
  "Qarz to'landi": "Долг погашен",
  "To'lov summasi": "Сумма платежа",
  "Haridorlar hisobi va qarz limitsiyasi boshqaruvi": "Учет покупателей и управление лимитом долга",
  "Jami mijozlar": "Всего клиентов",
  "Qarzdorlar": "Должники",
  "Jami qarz": "Общий долг",
  "Mijoz ismi yoki telefon raqami bo'yicha...": "По имени клиента или номеру телефона...",
  "Mijozlar yuklanmoqda...": "Загрузка клиентов...",
  "Hech kim topilmadi": "Никто не найден",
  "so'rovi bo'yicha mijoz yo'q": "по запросу клиента нет",
  "Tizimda hozircha mijozlar mavjud emas": "В системе пока нет клиентов",
  "Mijoz qo'shish": "Добавить клиента",
  "Rasm yuklash": "Загрузить фото",
  "To'liq ism": "Полное имя",
  "Mijoz F.I.Sh...": "Ф.И.О. клиента...",
  "Telegram ID raqami": "Telegram ID номер",
  "Masalan:": "Например:",
  "Yashash joyi (Manzil)": "Место жительства (Адрес)",
  "Shahar, ko'cha, uy raqami...": "Город, улица, номер дома...",
  "Qarz limiti (UZS)": "Лимит долга (UZS)",
  "0 = limitsiz qarz": "0 = безлимитный долг",
  "Izoh / Eslatma": "Примечание / Заметка",
  "Mijoz haqida qo'shimcha ma'lumot...": "Дополнительная информация о клиенте...",
  "LIMIT!": "ЛИМИТ!",
  "QARZ": "ДОЛГ",
  "Qarz yo'q": "Нет долга",
  "Mijoz qo'shishda xatolik yuz berdi": "Произошла ошибка при добавлении клиента",
  "Rasm yuklash xatoligi:": "Ошибка загрузки изображения:",
  "Rasmni yuklashda xatolik yuz berdi": "Произошла ошибка при загрузке изображения",
  "Mijoz ismi kiritilishi shart": "Имя клиента обязательно к вводу",
  "Telefon raqami noto'g'ri (998xxxxxxxxx shaklida bo'lishi shart)": "Неверный номер телефона (должен быть в формате 998xxxxxxxxx)",
  "Orqaga": "Назад",
  "Mijoz yuklanmoqda...": "Загрузка клиента...",
  "Izoh:": "Примечание:",
  "Tizim rahbari o'chirish so'rovingizni rad etdi.": "Администратор системы отклонил ваш запрос на удаление.",
  "O'chirish so'rovi rahbar tasdig'ini kutmoqda.": "Запрос на удаление ожидает подтверждения руководителя.",
  "Mijoz joriy qarzi:": "Текущий долг клиента:",
  "To'lanayotgan summa (UZS) *": "Оплачиваемая сумма (UZS) *",
  "To'lov bo'yicha izoh (ixtiyoriy)...": "Комментарий по платежу (необязательно)...",
  "To'g'ri to'lov summasini kiriting": "Введите корректную сумму платежа",
  "To'lovni saqlashda xato yuz berdi": "Произошла ошибка при сохранении платежа",
  "Mijoz ma'lumotlarini saqlashda xato": "Ошибка при сохранении данных клиента",
  "O'chirishda xato yuz berdi": "Произошла ошибка при удалении",
  "O'chirish so'rovini yuborishda xato yuz berdi": "Произошла ошибка при отправке запроса на удаление",
  "Ism kiritilishi shart": "Имя обязательно к вводу",
  "Telefon kiritilishi shart": "Телефон обязателен к вводу",
  "Mijoz ma'lumotlarini tahrirlash": "Редактировать данные клиента",
  "Ism F.I.Sh": "Имя Ф.И.О.",
  "Shahar, ko'cha, uy...": "Город, улица, дом...",
  "0 = cheksiz limit": "0 = бесконечный лимит",
  "Eslatma / Izoh": "Заметка / Примечание",
  "Izoh...": "Примечание...",
  "So'rov yuborildi!": "Запрос отправлен!",
  "Rahbar tasdiqlasa, mijoz butunlay o'chiriladi.": "После подтверждения руководителем клиент будет полностью удален.",
  "Yaxshi": "Хорошо",
  "O'chirish so'rovi": "Запрос на удаление",
  "Raxbar tasdig'i kutiladi": "Ожидается подтверждение руководителя",
  "mijozini o'chirish bo'yicha tizim rahbariga so'rov yuborilsinmi?": "отправить запрос администратору на удаление клиента?",
  "Mijozni o'chirish": "Удаление клиента",
  "mijozini butunlay o'chirasizmi?": "удалить клиента навсегда?",
  "Mijoz tafsilotlari": "Детали клиента",
  "To'lov qabul qilish": "Принять платеж",
  "Ko'chirma": "Выписка",
  "Nasiyalar": "Долги",
  "To'lovlar": "Платежи",
  "Yangi savdo": "Новая продажа",
  "Nasiyaga sotilgan mahsulotlar yo'q": "Нет товаров, проданных в долг",
  "Kassa to'lovi:": "Платеж через кассу:",
  "qarzga": "в долг",
  "Qarz to'lovlari tarixi mavjud emas": "История платежей по долгам отсутствует",
  "Qarz qaytarilishi": "Возврат долга",
  "to'landi": "оплачено",
  "Qarz limiti:": "Лимит долга:",
  "Qarz limitiga yaqin": "Близко к лимиту долга",
  "Mijoz qarzdorligi": "Задолженность клиента",
  "To'lov turi / Izoh": "Способ оплаты / Примечание",
  "Sotuvchi:": "Продавец:",
  "Tizim orqali shakllantirildi": "Сформировано через систему",
  "Nasiyaga olingan savdolar": "Продажи в долг",
  "Sotilgan sana": "Дата продажи",
  "Tovarlar miqdori": "Количество товаров",
  "To'langan qism": "Оплаченная часть",
  "To'lov sanasi": "Дата оплаты",

  // Settings
  "Tizim parametrlari, mavzu va hisob ma'lumotlarini sozlash": "Настройка параметров системы, темы и учетных записей",
  "Obuna ma'lumotlari": "Информация о подписке",
  "Ko'rinish (Mavzu)": "Внешний вид (Тема)",
  "Kunduzgi": "Дневная",
  "Tungi": "Ночная",
  "Tizim": "Системная",
  "Do'kon ma'lumotlari": "Информация о магазине",
  "Do'kon nomi": "Название магазина",
  "Izoh / Subtitr": "Примечание / Подзаголовок",
  "Do'kon manzili": "Адрес магазина",
  "Sozlamalarni saqlash": "Сохранить настройки",
  "Saqlandi ✓": "Сохранено ✓",
  "Sotuvchilar ro'yxati": "Список продавцов",
  "Sotuvchi qo'shish": "Добавить продавца",
  "Kutayotgan ishchi arizalari mavjud emas": "Нет ожидающих заявок работников",
  "O'chirish so'rovlari": "Запросы на удаление",
  "Kutayotgan o'chirish so'rovlari mavjud emas": "Нет ожидающих запросов на удаление",
  "Ishchilar boshqaruvi": "Управление работниками",
  "Hisob ma'lumotlari": "Учетные данные",
  "Roli:": "Роль:",
  "Do'kon ID raqami (Worker login uchun):": "ID магазина (для входа работника):",
  "Menejer Logini:": "Логин менеджера:",
  "Tizimdan chiqish": "Выйти из системы",
  "Hisobni o'chirish": "Удалить аккаунт",
  "Ilova tili": "Язык приложения",
  "O'lchov birliklari": "Единицы измерения",
  "Savat va savdoda ishlatiladigan o'lchov birliklarini boshqarish:": "Управление единицами измерения, используемыми в корзине и продажах:",
  "Ilova versiyasi": "Версия приложения",
  "Joriy versiya:": "Текущая версия:",
  "Oxirgi yangilanish:": "Последнее обновление:",
  "Biz haqimizda": "О нас",
  "Administrator tel:": "Тел. администратора:",
  "Barcha Ishni bizga qo'yib bering siz esa dam oling!": "Оставьте всю работу нам, а сами отдыхайте!",

  // Missing keys for POS & Guards & Forms
  "bo'limi": "раздел",
  "Bu bo'lim": "Этот раздел",
  "faqat faol obuna bilan ishlaydi": "работает только с активной подпиской",
  "Avval obuna paketini sotib oling, so'ng admin tomonidan faollashtiriladi": "Сначала приобретите пакет подписки, затем он будет активирован администратором",
  "Obuna sotib olish": "Купить подписку",
  "Admin telefon raqami:": "Номер телефона администратора:",
  "To'lovni amalga oshiring, admin obunangizni faollashtiradi": "Произведите оплату, администратор активирует вашу подписку",
  "Admin telefon raqami hali kiritilmagan.": "Номер телефона администратора еще не добавлен.",
  "Keyinroq urinib ko'ring.": "Пожалуйста, попробуйте позже.",
  "Qayta urinish": "Повторить попытку",
  "Profilni yo'q qilish": "Уничтожить профиль",
  "Barcha ma'lumotlaringiz — login, parol, do'kon ID, sotuvchilar — butunlay o'chiriladi. Bu amal qaytarib bo'lmaydi!": "Все ваши данные — логин, пароль, ID магазина, продавцы — будут полностью удалены. Это действие необратимо!",
  "Profilni o'chirishda xato yuz berdi. Qayta urinib ko'ring.": "Произошла ошибка при удалении профиля. Пожалуйста, попробуйте еще раз.",
  "Siz tizim tomonidan": "Вы полностью заблокированы",
  "to'liq bloklandingiz": "системой",
  "Siz tizim tomonidan to'liq bloklandingiz": "Вы полностью заблокированы системой",
  "Barcha imkoniyatlar cheklangan.": "Все возможности ограничены.",
  "Faqat profilingizni butunlay o'chirishingiz mumkin.": "Вы можете только полностью удалить свой профиль.",
  "Administrator tomonidan bloklangan": "Заблокировано администратором",
  "Tizimdan chiqishni xohlaysizmi?": "Вы действительно хотите выйти из системы?",
  "Obuna muddati tugagan": "Срок подписки истек",
  "Tizimdan foydalanish uchun obunangizni yangilang.": "Обновите подписку для использования системы.",
  "Administrator bilan bog'laning.": "Свяжитесь с администратором.",
  "Tugagan:": "Истек:",
  "Chiqish": "Выйти",
  "Obuna bugun tugaydi! Yangilang.": "Подписка заканчивается сегодня! Обновите.",
  "Obuna": "Подписка",
  "kun ichida tugaydi": "дней заканчивается",
  "Kamera orqali skanerlash": "Сканирование через камеру",
  "Kameraga ruxsat so'ralmoqda...": "Запрос разрешения на камеру...",
  "Kamerani shtrix-kodga qarating": "Направьте камеру на штрих-код",
  "Brauzeringiz kameradan shtrix-kodni o'qishni qo'llab-quvvatlamaydi. Jismoniy skaner qurolidan foydalaning.": "Ваш браузер не поддерживает чтение штрих-кода с камеры. Используйте физический сканер.",
  "Kameraga ulanib bo'lmadi. Ruxsatlarni tekshiring.": "Не удалось подключиться к камере. Проверьте разрешения.",
  "Chek Telegram orqali mijozga muvaffaqiyatli yuborildi!": "Чек успешно отправлен клиенту в Telegram!",
  "Chekni yuborib bo'lmadi. Telegram orqali qo'lda ulash oynasini ochamiz.": "Не удалось отправить чек. Открываем окно ручной отправки в Telegram.",
  "Telegram-ga yuborishda xatolik yuz berdi. Qo'lda ulash oynasini ochamiz.": "Произошла ошибка при отправке в Telegram. Открываем окно ручной отправки.",
  "To'g'ri miqdor kiriting (masalan: 1.5)": "Введите правильное количество (например: 1.5)",
  "Tovarlar bo'limidan mahsulot qo'shing yoki yuqoridagi skaner tugmasini bosing": "Добавьте товар из раздела товаров или нажмите кнопку сканера выше",
  "Tovar tanlash": "Выбрать товар",
  "Mijozni saqlash va tanlash": "Сохранить и выбрать клиента",
  "Kamida bitta o'lchov birligi faol qolishi shart!": "Хотя бы одна единица измерения должна оставаться активной!",
  "O'chirilgan": "Отключен",
  "Faol": "Активен",
  "Sotuvchi ismi *": "Имя продавца *",
  "Telefon raqami *": "Номер телефона *",
  "Sotuvchi ismi": "Имя продавца",
  "Sotuvchini tahrirlash": "Редактировать продавца",
  "Yangi sotuvchi qo'shish": "Добавить нового продавца",
  "Sotuvchini o'chirish": "Удалить продавца",
  "Haqiqatdan ham sotuvchi": "Вы действительно хотите удалить продавца",
  "ni ro'yxatdan o'chirasizmi?": "из списка?",
  "Yo'q": "Нет",
  "Ishchini tizimdan o'chirish": "Удалить сотрудника из системы",
  "Haqiqatdan ham ishchi": "Вы действительно хотите удалить сотрудника",
  "ni o'chirib tashlaysizmi? U do'kon hisobiga boshqa kira olmaydi.": "? Он больше не сможет войти в аккаунт магазина.",
  "Bekor": "Отмена",
  "Tizimdan butunlay o'chib ketish": "Полностью удалиться из системы",
  "Menejer hisobi va unga tegishli barcha do'kon tovarlari, ishchilar, savdo tarixi va mijozlar ma'lumotlari serverdan butunlay o'chiriladi. Bu amalni qaytarib bo'lmaydi.": "Учетная запись менеджера и все связанные с ней товары, сотрудники, история продаж и данные клиентов будут полностью удалены. Это действие необратимо.",
  "Profil qalinligi (mm, ixtiyoriy)": "Толщина профиля (мм, опционально)",
  "Navi yoki Turi (ixtiyoriy)": "Сорт или Тип (опционально)",
  "Brend / Ishlab chiqaruvchi (ixtiyoriy)": "Бренд / Производитель (опционально)",
  "Masalan: Olma, Kartoshka...": "Например: Яблоки, Картофель...",
  "Masalan: Alyumin profil, Kabel...": "Например: Алюминиевый профиль, Кабель...",
  "Masalan: iPhone 15 Pro Max qopqoq": "Например: Чехол для iPhone Pro Max 15",
  "Masalan: Samarqand, Lazer...": "Например: Самаркандский, Лазер...",
  "Masalan: Xitoy, O'zbekiston...": "Например: Китай, Узбекистан...",
  "Masalan: Apple, Samsung, Xiaomi": "Например: Apple, Samsung, Xiaomi",
  "Nomi kiritilishi shart": "Имя обязательно к вводу",
  "Tan narxini to'g'ri kiriting": "Введите корректную себестоимость",
  "Sotuv narxini to'g'ri kiriting": "Введите корректную цену продажи",
  "Miqdorni to'g'ri kiriting": "Введите корректное количество",
  "Mahsulot parametrlari, narxlari va ombor qoldig'ini kiriting": "Введите параметры товара, цены и остаток на складе",
  "Saqlashda xato yuz berdi": "Произошла ошибка при сохранении",
  "Tahrirlashda xato yuz berdi": "Произошла ошибка при редактировании",
  "Ruxsat berish": "Разрешить",
  "Rad qilish": "Отклонить",
  "Savdo o'chirish": "Удаление продажи",
  "Ishchi:": "Сотрудник:",
  "Nomi:": "Название:",
  "Ismi:": "Имя:",
  "Tranzaksiya ID:": "ID Транзакции:",
  "Menejer Paroli:": "Пароль менеджера:",
  "\"${name}\" mahsulotida stok qolmagan": "Товара \"${name}\" нет в наличии",
  "Stok yetarli emas. Faqat ${quantity} ${unit} mavjud": "Недостаточно на складе. В наличии только ${quantity} ${unit}",
  "\"${barcode}\" shtrix-kodi bo'yicha mahsulot topilmadi.": "Товар со штрих-кодом \"${barcode}\" не найден.",
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("uz");
  const { managerId } = useAuth();
  const { settings } = useSettings(managerId);

  // Load language preference initially from localStorage
  useEffect(() => {
    const stored = localStorage.getItem("smartboss_language") as Language | null;
    if (stored === "uz" || stored === "ru") {
      setLanguageState(stored);
    }
  }, []);

  // Sync with store settings when it loads
  useEffect(() => {
    if (settings && settings.appLanguage) {
      setLanguageState(settings.appLanguage);
      localStorage.setItem("smartboss_language", settings.appLanguage);
    }
  }, [settings?.appLanguage]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("smartboss_language", lang);
  };

  const t = (text: string): string => {
    if (language === "ru") {
      // Clean text to avoid lookup failures due to extra whitespace
      const trimmed = text.trim();
      if (dictionary[trimmed]) {
        // Restore original leading/trailing spacing if any
        const leadingSpace = text.match(/^\s*/)?.[0] || "";
        const trailingSpace = text.match(/\s*$/)?.[0] || "";
        return `${leadingSpace}${dictionary[trimmed]}${trailingSpace}`;
      }
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    // Return fallback if context is not loaded yet
    return {
      language: "uz" as Language,
      setLanguage: () => {},
      t: (text: string) => text,
    };
  }
  return ctx;
}
