const colors = {
  light: {
    text: "#1A1A2E",
    tint: "#1565C0",
    background: "#F4F6FB",
    foreground: "#1A1A2E",
    card: "#FFFFFF",
    cardForeground: "#1A1A2E",
    primary: "#1565C0",
    primaryLight: "#1976D2",
    primaryForeground: "#FFFFFF",
    secondary: "#E3F2FD",
    secondaryForeground: "#0D47A1",
    muted: "#F1F3F8",
    mutedForeground: "#64748B",
    accent: "#42A5F5",
    accentForeground: "#FFFFFF",
    destructive: "#D32F2F",
    destructiveForeground: "#FFFFFF",
    success: "#2E7D32",
    successForeground: "#FFFFFF",
    warning: "#F57C00",
    warningForeground: "#FFFFFF",
    border: "#DDE3EE",
    input: "#DDE3EE",
    surface: "#FFFFFF",
    surfaceVariant: "#EEF2FA",
    onSurface: "#1A1A2E",
    headerBg: "#1565C0",
    headerText: "#FFFFFF",
  },
  dark: {
    text: "#E8EAF6",
    tint: "#42A5F5",
    background: "#0F1117",
    foreground: "#E8EAF6",
    card: "#1A1F2E",
    cardForeground: "#E8EAF6",
    primary: "#1976D2",
    primaryLight: "#42A5F5",
    primaryForeground: "#FFFFFF",
    secondary: "#0D1B3E",
    secondaryForeground: "#90CAF9",
    muted: "#252B3B",
    mutedForeground: "#94A3B8",
    accent: "#1565C0",
    accentForeground: "#FFFFFF",
    destructive: "#EF5350",
    destructiveForeground: "#FFFFFF",
    success: "#43A047",
    successForeground: "#FFFFFF",
    warning: "#FFA726",
    warningForeground: "#FFFFFF",
    border: "#2A3050",
    input: "#2A3050",
    surface: "#1A1F2E",
    surfaceVariant: "#252B3B",
    onSurface: "#E8EAF6",
    headerBg: "#0F1117",
    headerText: "#E8EAF6",
  },
  radius: 12,
};

export default colors;
