const colors = {
  light: {
    text: "#0F172A",
    tint: "#2563EB",
    background: "#F4F7FA",
    foreground: "#0F172A",
    card: "#FFFFFF",
    cardForeground: "#0F172A",
    primary: "#2563EB",
    primaryLight: "#60A5FA",
    primaryForeground: "#FFFFFF",
    secondary: "#E2E8F0",
    secondaryForeground: "#1E293B",
    muted: "#F1F5F9",
    mutedForeground: "#64748B",
    accent: "#38BDF8",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    success: "#10B981",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
    warningForeground: "#FFFFFF",
    border: "#E2E8F0",
    input: "#F8FAFC",
    surface: "#FFFFFF",
    surfaceVariant: "#F1F5F9",
    onSurface: "#0F172A",
    headerBg: "#FFFFFF",
    headerText: "#0F172A",
  },
  dark: {
    text: "#ffffff",
    tint: "#3b82f6",
    background: "#0b0f19",
    foreground: "#ffffff",
    card: "rgba(17, 24, 39, 0.75)",
    cardForeground: "#ffffff",
    primary: "#3b82f6",
    primaryLight: "#60a5fa",
    primaryForeground: "#ffffff",
    secondary: "#1e293b",
    secondaryForeground: "#93c5fd",
    muted: "#1f2937",
    mutedForeground: "#9ca3af",
    accent: "#3b82f6",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    success: "#10b981",
    successForeground: "#ffffff",
    warning: "#f97316",
    warningForeground: "#ffffff",
    border: "rgba(255, 255, 255, 0.08)",
    input: "rgba(255, 255, 255, 0.08)",
    surface: "#111827",
    surfaceVariant: "#1f2937",
    onSurface: "#ffffff",
    headerBg: "#0b0f19",
    headerText: "#ffffff",
  },
  radius: 12,
};

export default colors;
